name: deploy page

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      
      - name: Credentials github
        run: |
          git config --global user.email ${{ secrets.EMAIL_GITHUB }}
          git config --global user.name ${{ secrets.USER_GITHUB }}
      
      - name: Deploy 🚀
        run: |
          npm run deploy